services:
#   mongo:
#      image: mongo
#      restart: always
#      volumes:
#        - mongo-db:/data/db
#      environment:
#        MONGO_INITDB_ROOT_USERNAME: root
#        MONGO_INITDB_ROOT_PASSWORD: example

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#       ME_CONFIG_BASICAUTH_ENABLED: true
#       ME_CONFIG_BASICAUTH_USERNAME: root
#       ME_CONFIG_BASICAUTH_PASSWORD: example
#     depends_on:
#        - mongo

  Postgres:
     image: postgres
     restart: always
     environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: password
     volumes:
       - postgres-db:/var/lib/postgresql/data
     
       
  redis:
      image: redis
    

  nginx:
   image: nginx:stable-alpine
   ports:
     - "80:80"
   volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
     - nodeapp
     - redis
   
  nodeapp:
    #  container_name: nodeapp-container 
    #  ports:
    #     - 4000:4000
     image: mramadan10/node-docker
     env_file:
       - ./.env
     depends_on:
     - Postgres
     
       
volumes:
  mongo-db:
  postgres-db:

